concessionnaire/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from voiture import views as voiture_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', voiture_views.VoitureView.as_view(), name='index'),
    path('assistance/', voiture_views.AssistanceView.as_view(), name='assistance'),
    path('concession/', voiture_views.ConcessionView.as_view(), name='concession'),
    path('voiture/', include('voiture.urls', namespace='voiture')),
    path('marque/', include('marque.urls', namespace='marque')),
    #path('__debug__/', include('debug_toolbar.urls')),
    path('utilisateurs/', include('utilisateurs.urls', namespace='utilisateurs')),
] 


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


'''
On utilise souvent un nom pour les apps quand on écrit plusieurs applications
et dont les noms des urls spnt les memes. Alors les app_namme permettent de se
rediriger vers cet url selin de nom de l'app defini
'''

marque/urls.py
from django.urls import path
from . import views


app_name = 'marque'


urlpatterns = [
	# post views
	path('<int:pk>/', views.MarqueDetailView.as_view(), name='detail'),
	path('', views.MarqueListView.as_view(), name='list'),
	path('add/', views.MarqueCreateView.as_view(), name='add'),
	path('update/<int:pk>/', views.MarqueUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/', views.MarqueDeleteView.as_view(), name="delete"),
]

utilisateurs/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# Ceci est le nom de l'app qaund on veut appeler les diiefrents urls qu'il contient
app_name='utilisateurs'

urlpatterns = [
	# post views
	path('', views.dashboard, name='dashboard'),
	path('edit/', views.edit, name='edit'),
	path('login/', auth_views.LoginView.as_view(template_name="Utilisateurs/login.html"), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name="Utilisateurs/logout.html"), name='logout'),
	path('register/', views.RegistrationView.as_view(), name="register"),
	path('register_done/', views.RegistrationDone.as_view(), name="register_done"),

	path('password_change/', auth_views.PasswordChangeView.as_view(template_name="Utilisateurs/password_change.html"), name='password_change'),
	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name="Utilisateurs/password_change_done.html"), name='password_change_done'),

	path('password_reset/', auth_views.PasswordResetView.as_view(template_name="Utilisateurs/password_reset.html"), name='password_reset'),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="Utilisateurs/password_reset_done.html"), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="Utilisateurs/password_reset_confirm.html"), name='password_reset_confirm'),
	path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="Utilisateurs/password_reset_complete.html"), name='password_reset_complete'),
]

utilisateurs/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	date_of_birth = models.DateField(blank=True, null=True)
	photo = models.ImageField(upload_to='media/uploads/users/%Y/%m/%d/', blank=True)

	def __str__(self):
		return f'Profile for user {self.user.username}'

utilisateurs/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


# Classe permettant de definir réellement les inputs de type date sur date
class DateInput(forms.DateInput):
	input_type='date'


# Formulaire de modifications des infos de l'utilisateur
class UserEditForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email')
		widgets = {

			'first_name': forms.TextInput(
		    	attrs={
		    		'class': 'form-control first_name',
		    	}
		    ),
		    'last_name': forms.TextInput(
		    	attrs={
		    		'class': 'form-control last_name',
		    	}
		    ),
		    'email': forms.EmailInput(attrs={
		        'class': 'form-control email',
		    }),
		}


# Formulaire de profil utilisateur		
class ProfileEditForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('date_of_birth', 'photo')
		widgets = {

			'photo': forms.FileInput(
		    	attrs={
		    		'class': 'form-control',
		    	}
		    ),
		    'date_of_birth': DateInput(
		    	attrs={
		        	'class': 'form-control',
		    }),
		}


# Formulaire de connexion utilisateur
class LoginForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',}))
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',}))


# Formulaire d'inscription d'utilisateur
class UserRegistrationForm(forms.ModelForm):
	password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'password', 'name': 'password',}))
	password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput(attrs={'class': 'form-control','id': 'confirm_password', 'name': 'confirm_password',}))

	class Meta:
		model = User
		fields = ('username', 'first_name', 'email')
		widgets = {

			'username': forms.TextInput(
		    	attrs={
		    		'class': 'form-control',
					'id': 'username',
					'name': 'username',
		    	}
		    ),
		    'first_name': forms.TextInput(
		    	attrs={
		    		'class': 'form-control',
					'id': 'first_name',
					'name': 'firstname',
		    	}
		    ),
		    'email': forms.EmailInput(attrs={
		        'class': 'form-control',
				'id': 'email',
				'name': 'email',
		    }),
		}

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password'] != cd['password2']:
			raise forms.ValidationError('Passwords don\'t match.')
		return cd['password2']

utilisateurs/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.models import User

# Vue ddu dashboard définie sous forme de fonction
@login_required
def dashboard(request):
	profile = Profile.objects.get(user=request.user)
	return render(request,'Utilisateurs/dashboard.html', {'profile': profile})


# Vue d'édition des informations de l'utilisateur
@login_required
def edit(request):
	if request.method == 'POST':
		#Cette partie appelle le formulaire d'edition de l'utilisateur avec pour inistance l'user actuellemnt connecté
		user_form = UserEditForm(instance=request.user, data=request.POST)
		profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
	else:
		user_form = UserEditForm(instance=request.user)
		profile_form = ProfileEditForm(instance=request.user.profile)
	return render(request, 'Utilisateurs/edit.html', {'user_form': user_form, 'profile_form': profile_form})

# Vue de creation d'utilisateur
class RegistrationView(View):
	form_class = UserRegistrationForm
	template_name = 'utilisateurs/register.html'

	def get(self, request, *args, **kwargs):
		return render(request, self.template_name, {'form': self.form_class})

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)
		if form.is_valid():
			user = form.save(commit=False)

			user.set_password(form.cleaned_data['password'])

			user.save()

			Profile.objects.create(user=user)

			return redirect('utilisateurs:register_done')
		return render(request, self.template_name, {'form': self.form_class})


# Vue de redirection de l'utilisation une fois le compte proprement créé.
class RegistrationDone(View):
	template_name='utilisateurs/register_done.html'

	def get(self, request, *args, **kwargs):
		return render(request, self.template_name)

templates/Utilisateurs/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
	<h1 class="fs-3 fw-bolder text-center">Dashboard</h1>
	<p class="text-center">Bienvenue sur votre profile.</p>
	<div>
		<form method="post" class="offset-md-3 row col-md-9 px-3" enctype="multipart/form-data">
			<div class="row mb-3">
				{% if profile.image %}
				<div class="offset-2 col-md-5" style="height: 14rem">
					<img class="img-responsive" src="{{ profile.photo.url }}">
				</div>
				{% endif %}
			</div>
			<div class="row mb-3">
				<div class="col-md-4">
					<label class="form-label">First name:</label>
					<input class="form-control" type="text" value="{{ user.first_name }}" disabled>
				</div>
				<div class="col-md-4">
					<label class="form-label">Last name:</label>
					<input class="form-control" type="text" value="{{ user.last_name }}" disabled>
				</div>
			</div>
			<div class="row mb-3">
				<div class="col-md-4">
					<label class="form-label">Email :</label>
					<input class="form-control" type="email" value="{{ user.email }}" disabled>
				</div>
				<div class="col-md-4">
					<label class="form-label">Date of Birth:</label>
					<input class="form-control" type="text" value="{{ profile.date_of_birth|date:"m-d-Y" }}" disabled>
				</div>
			</div>
			<div class="row mb-3">
				<div class="col-md-4">
					<label class="form-label">Username :</label>
					<input class="form-control" type="text" value="{{ user.username }}" disabled>
				</div>
				<div class="col-md-4">
					<label class="form-label">Password :</label>
					<input class="form-control" type="password" value="" disabled>
				</div>
			</div>
			<div class="row mb-3">
				<div class="col-md-4">
					<button class="btn btn-success offset-4 mb-3" type="button"><a class="text-decoration-none text-white" href="{% url "utilisateurs:edit" %}">Editer</a>
					</button>
				</div>
				<div class="col-md-4">
					<button class="btn btn-danger offset-2" type="button"><a class="text-decoration-none text-white" href="{% url "utilisateurs:password_change" %}">Change password</a>
					</button>
				</div>
			</div>
		</form>
	</div>
{% endblock %}

templates/Utilisateurs/edit.html
{% extends "base.html" %}

{% block title %}Edit your account{% endblock %}

{% block content %}
	<h1 class="fs-3 fw-bolder text-center">Edit your account</h1>
	<hr class="offset-md-4 offset-3 border-2 text-primary col-6 col-md-4  rounded-pill" style="height: 3px;">
	<div class="offset-md-2 offset-sm-2">
		<form method="post" class="offset-md-1 row col-md-8 col-sm-8 col px-3 shadow pt-3 mx-2 mx-md-5" enctype="multipart/form-data">
		{{ user_form.as_p }}
		{{ profile_form.as_p }}
		{% csrf_token %}
		<input class="btn btn-primary col-6 col-md-8 offset-md-2 offset-3 mb-3" type="submit" value="Save changes">
		</form>
	</div>
{% endblock %}

templates/Utilisateurs/login.html
{% extends "base.html" %}

{% block title %}Se connecter{% endblock %}

{% block content %}
	<h1 class="fs-3 fw-bolder text-center">Se connecter</h1>
	<hr class="offset-md-4 offset-3 border-2 text-primary col-6 col-md-4  rounded-pill" style="height: 3px;">
	<div class="offset-md-2">
		<form method="post" class="offset-md-1 row col-md-8 col-sm-6 col px-3 shadow pt-3 mx-2 mx-md-5" enctype="multipart/form-data">
				<div class="mb-3">
					<label class="form-label">Username :</label>
					<input class="form-control" type="text" id="username" name="username" placeholder="Username">
				</div>
				<div class="mb-3">
					<label class="form-label">Password :</label>
					<input class="form-control" type="password" id="password" name="password" placeholder="Password">
				</div>					
			{% csrf_token %}
			<input class="btn btn-primary col-6 offset-3" type="submit" value="Log in">
			<p class="form-text">Vous n'aviez pas encore de compte ? Cliquer ici pour <a class="text-decoration-none" href="{% url "utilisateurs:register" %}">vous inscrire</a></p>
		</form>
	</div>
{% endblock %}

templates/Utilisateurs/logout.html
{% extends "base.html" %}

{% block title %}Logged out{% endblock %}

{% block content %}
	<div class="mx-4">
		<h1 class="fs-3 fw-bolder text-center">Déconnexion</h1>
		<p class="offset-2">
			Vous avez été déconnecté avec succès.
			Redirigez vous vers cette page pour <a class="text-decoration-none" href="{% url "utilisateurs:login" %}">vous connecter</a>.
		</p>
	</div>
{% endblock %}

templates/Utilisateurs/password_change.html
{% extends "base.html" %}

{% block title %}Changer son mot de passe{% endblock %}

{% block content %}
	<h1 class="fs-3 fw-bolder">Changer son mot de passe</h1>
	<hr class="offset-md-4 offset-3 border-2 text-primary col-6 col-md-4  rounded-pill" style="height: 3px;">
	<div class="offset-md-2">
		<form method="post" class="offset-md-1 row col-md-8 col-sm-6 col px-3 shadow pt-3 mx-2 mx-md-5" enctype="multipart/form-data">
			{% for field in form %}
				<div class="mb-3">
					{{ field.errors }}
					<label class="form-label">{{ field.label }}</label>
					{{ field }}
				</div>				
			{% endfor %}
			<input class="btn btn-primary" type="submit" value="Change">
			{% csrf_token %}
		</form>
	</div>
{% endblock %} 

templates/Utilisateurs/password_change_done.html
{% extends "base.html" %}

{% block title %}Password changed{% endblock %}

{% block content %}
	<h1 class="fs-3 fw-bolder">Password changed</h1>
	<p>Your password has been successfully changed.</p>
{% endblock %}

templates/Utilisateurs/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Password reset{% endblock %}

{% block content %}
	<h1 class="fs-3 fw-bolder">Password set</h1>
	<p>Your password has been set. You can
	<a href="{% url "utilisateurs:login" %}">log in now</a></p>
{% endblock %}

templates/Utilisateurs/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}Reset your password{% endblock %}

{% block content %}
	<h1 class="fs-3 fw-bolder">Reset your password</h1>
	{% if validlink %}
		<p>Please enter your new password twice:</p>
		<div class="offset-3">
			<form method="post" class="row col-md-6 px-3" enctype="multipart/form-data">
				{% for field in form %}
					<div class="mb-3">
						{{ field.errors }}
						<label class="form-label">{{ field.label }}</label>
						{{ field }}
					</div>				
				{% endfor %}
				<input class="btn btn-primary" type="submit" value="Change your password">
				{% csrf_token %}
			</form>
		</div>
	{% else %}
		<p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</p>
	{% endif %}
{% endblock %}

templates/Utilisateurs/password_reset_email.html
Someone asked for password reset for email {{ email }}. 
Follow the link below: {{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.get_username }}

templates/Utilisateurs/password_reset_email_done.html
{% extends "base.html" %}

{% block title %}Reset your password{% endblock %}

{% block content %}
	<h1 class="fs-3 fw-bolder">Reset your password</h1>
	<p>We've emailed you instructions for setting your password.</p>
	<p>If you don't receive an email, please make sure you've entered
	the address you registered with.</p>
{% endblock %}

templates/Utilisateurs/password_reset_form.html
{% extends "base.html" %}

{% block title %}Reset your password{% endblock %}

{% block content %}
	<h1 class="fs-3 fw-bolder">Forgotten your password?</h1>
	<p>Enter your e-mail address to obtain a new password.</p>
	<div class="offset-3">
		<form method="post" class="row col-md-6 px-3" enctype="multipart/form-data">
			{% for field in form %}
				<div class="mb-3">
					{{ field.errors }}
					<label class="form-label">{{ field.label }}</label>
					{{ field }}
				</div>				
			{% endfor %}
			<input class="btn btn-primary" type="submit" value="Send e-mail">
			{% csrf_token %}
		</form>
	</div>
{% endblock %}

templates/Utilisateurs/register.html
{% extends "base.html" %}

{% block title %}Creer son compte{% endblock %}

{% block content %}
	<div class="mt-3 mx-3">
		<h1 class="text-center fs-3 fw-bolder">Créer son compte</h1>
		<hr class="offset-md-4 offset-3 border-2 text-primary col-6 col-md-4  rounded-pill" style="height: 3px;">
		<div class="offset-md-2">
			<form method="post" class="offset-md-1 row col-md-8 col-sm-6 col px-3 shadow pt-3 mx-2 mx-md-5" enctype="multipart/form-data">
				{% for field in form %}
					<div class="mb-3">
						<label class="form-label">{{ field.label }}</label>
						{{ field }}
						<small id="{{ field.label }}" class="form-text text-muted invalid-feedback"></small>
					</div>				
				{% endfor %}
				<input class="btn btn-primary mb-3 col-md-8 offset-md-2" type="submit" value="Creer son compte" id="submitbtn">
				<p class="form-text">Vous disposez déjà d'un compte ? Cliquer ici pour <a class="text-decoration-none" href="{% url "utilisateurs:login" %}">vous connecter</a></p>
				{% csrf_token %}
			</form>
		</div>
	</div>
{% endblock %}

templates/Utilisateurs/register_done.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
	<h1 class="fs-3 fw-bolder text-center">Welcome {{ user.first_name }}!</h1>
	<p>Your account has been successfully created. Now you can <a
	href="{% url "utilisateurs:login" %}">log in</a>.</p>
{% endblock %}