concessionnaire/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from voiture import views as voiture_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', voiture_views.VoitureView.as_view(), name='index'),
    path('assistance/', voiture_views.AssistanceView.as_view(), name='assistance'),
    path('concession/', voiture_views.ConcessionView.as_view(), name='concession'),
    path('voiture/', include('voiture.urls', namespace='voiture')),
    path('marque/', include('marque.urls', namespace='marque')),
    #path('__debug__/', include('debug_toolbar.urls')),
    path('utilisateurs/', include('utilisateurs.urls', namespace='utilisateurs')),
] 


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


'''
On utilise souvent un nom pour les apps quand on écrit plusieurs applications
et dont les noms des urls spnt les memes. Alors les app_namme permettent de se
rediriger vers cet url selin de nom de l'app defini
'''

marque/urls.py
from django.urls import path
from . import views


app_name = 'marque'


urlpatterns = [
	# post views
	path('<int:pk>/', views.MarqueDetailView.as_view(), name='detail'),
	path('', views.MarqueListView.as_view(), name='list'),
	path('add/', views.MarqueCreateView.as_view(), name='add'),
	path('update/<int:pk>/', views.MarqueUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/', views.MarqueDeleteView.as_view(), name="delete"),
]

utilisateurs/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# Ceci est le nom de l'app qaund on veut appeler les diiefrents urls qu'il contient
app_name='utilisateurs'

urlpatterns = [
	# post views
	path('', views.dashboard, name='dashboard'),
	path('edit/', views.edit, name='edit'),
	path('login/', auth_views.LoginView.as_view(template_name="Utilisateurs/login.html"), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name="Utilisateurs/logout.html"), name='logout'),
	path('register/', views.RegistrationView.as_view(), name="register"),
	path('register_done/', views.RegistrationDone.as_view(), name="register_done"),

	path('password_change/', auth_views.PasswordChangeView.as_view(template_name="Utilisateurs/password_change.html"), name='password_change'),
	path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name="Utilisateurs/password_change_done.html"), name='password_change_done'),

	path('password_reset/', auth_views.PasswordResetView.as_view(template_name="Utilisateurs/password_reset.html"), name='password_reset'),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="Utilisateurs/password_reset_done.html"), name='password_reset_done'),
	path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="Utilisateurs/password_reset_confirm.html"), name='password_reset_confirm'),
	path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="Utilisateurs/password_reset_complete.html"), name='password_reset_complete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>ALPHA_ONE | {% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
	<link href="{% static "css/concessionnaire.css" %}" rel="stylesheet">
	<link href="{% static "bootstrap-icons/bootstrap-icons.css" %}" rel="stylesheet">
	<style>
	</style>
</head>
<body>
	{% include 'header.html' %}

	<section>{% block content %} {% endblock content %}</section>

	{% include 'footer.html' %}
</body>
</html>

templates/footer.html
{% load static %}
<section class="">
    {% if request.resolver_match.view_name == 'index' or request.resolver_match.view_name == 'assistance' %}
    <div class="mt-5 container">
        <div class="container bg-secondary rounded-3 text-white pt-5">
            <div class="container-fluid">
                <h2 class="text-center fs-2 fw-bolder">Se souscrire a la Newsletter</h2>
                <p class="col-8 offset-2">Rejoignez-nous a travers notre newsletter pour suivre directement nos nouvelles offres sur le marche ainsi que les promotions qio vous sont offertes.</p>
            </div>
            <form class="my-3 row pt-3 pb-5 justify-content-center" method="post">
                <div class="row-cols-2 mb-3 col-lg-6 offset-lg-0 col-md-6 offset-md-0">
                    <input class="form-control" type="email" name="email" placeholder="Your Email">
                </div>
                <div class="row-cols-3 col-lg-3 offset-lg-1 offset-md-1 col-md-3">
                    <button class="btn btn-primary w-100" type="button">Se souscrire </button>
                </div>
            </form>
        </div>
    </div>
    {% else %}
    <div></div>
    {% endif %}
	{% if request.resolver_match.view_name == 'index' or request.resolver_match.view_name == 'assistance' %}
    <div class="row mt-5">
        <div class="row col-xxl-8 col-xl-8 offset-xxl-2 offset-xl-2 text-center">
            <div class="align-content-center ms-3">
                Vous pouvez aussi nous contacter directement par telephone ou par sms sur le <a href="" class="text-decoration-none text-dark"><i class="bi bi-telephone fw-bolder">+22957131199</i></a>. <br> 
                Vous pouvez aussi nous joindre a travers nos reseaux sociaux.
            </div>
            <ul class="nav d-flex flex-row-reverse ">
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted"><i class="bi bi-whatsapp fw-bolder fs-3 text-success me-5"></i></a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted"><i class="bi bi-facebook fw-bolder fs-3 text-primary "></i></a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted"><i class="bi bi-instagram fw-bolder fs-3 text-danger "></i></a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted"><i class="bi bi-twitter fw-bolder fs-3 text-primary "></i></a></li>
            </ul>
        </div>
        <div class="offset-xxl-2 offset-xl-2">
        </div>
    </div>
	{% else %}
    <div></div>
    {% endif %}
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-5 mb-0 fs-6 form-text">© 10-20 TECHNOLOGIES <sup>.</sup> Tous droits réservés <sup>.</sup> 2023
        </p>

        <a href="{% url 'index' %}" class="col-md-3 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
    		<img src="{% static "images/logo.png"%}" class="rounded-3 img-responsive" width="60" height="60">
    	</a>

        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Categories</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Voitures</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">A Propos</a></li>
        </ul>
    </footer>
</section>
<script src="{% static "js/bootstrap.bundle.js"%}"></script>
<script src="{% static "js/jquery-3.6.0.min.js"%}"></script>
<script src="{% static "js/concessionnaire.js"%}"></script>

templates/header.html
{% load static %}

<header>
    <div></div>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}">
                <img src="{% static "images/logo.png"%}" class="rounded-3 img-responsive" width="60" height="60">
            </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if request.resolver_match.view_name == 'index' %}
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Accueil</a> {% else %}
                    <a class="nav-link" aria-current="page" href="{% url 'index' %}">Accueil</a> {% endif %}
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Marques
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for marque in marques %}
                            <li><a class="dropdown-item" href=" {% url 'marque:detail' marque.pk %} ">{{ marque.name }} </a></li>
                        {% endfor %}
                    </ul>
                  </li>
                <li class="nav-item">
                    {% if request.resolver_match.view_name == 'voiture:list' %}
                    <a class="nav-link active" href="{% url 'voiture:list' %}">Voitures</a> 
                    {% else %}
                    <a class="nav-link" href="{% url 'voiture:list' %}">Voitures</a> 
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">A Propos</a>
                </li>
            </ul>
            <div class="d-flex ">
                {% if user.is_authenticated %}
                <li class="list-unstyled"><a class="text-decoration-none" href="{% url 'utilisateurs:dashboard' %}"><i class="bi bi-person-fill"></i>{{user.username}}</a></li> &nbsp;&nbsp;
                <li class="list-unstyled"><a class="text-decoration-none" href="{% url 'utilisateurs:logout' %}">Deconnexion</a></li>
                {% else %}
                <li class="list-unstyled"><a class="text-decoration-none" href="{% url 'utilisateurs:login' %}">Se connecter</a></li>&nbsp;&nbsp; {% endif %}
            </div>
          </div>
        </div>
    </nav>
</header>