concessionnaire/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from voiture import views as voiture_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', voiture_views.VoitureView.as_view(), name='index'),
    path('assistance/', voiture_views.AssistanceView.as_view(), name='assistance'),
    path('concession/', voiture_views.ConcessionView.as_view(), name='concession'),
    path('voiture/', include('voiture.urls', namespace='voiture')),
    path('marque/', include('marque.urls', namespace='marque')),
    #path('__debug__/', include('debug_toolbar.urls')),
    path('utilisateurs/', include('utilisateurs.urls', namespace='utilisateurs')),
] 


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


'''
On utilise souvent un nom pour les apps quand on écrit plusieurs applications
et dont les noms des urls spnt les memes. Alors les app_namme permettent de se
rediriger vers cet url selin de nom de l'app defini
'''

marque/urls.py
from django.urls import path
from . import views


app_name = 'marque'


urlpatterns = [
	# post views
	path('<int:pk>/', views.MarqueDetailView.as_view(), name='detail'),
	path('', views.MarqueListView.as_view(), name='list'),
	path('add/', views.MarqueCreateView.as_view(), name='add'),
	path('update/<int:pk>/', views.MarqueUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/', views.MarqueDeleteView.as_view(), name="delete"),
]

marque/models.py
from django.db import models

# Create your models here.

marque/forms.py
from django import forms
from voiture.models import Marque

class MarqueForm(forms.ModelForm):

	class Meta:

		model = Marque

		fields = '__all__'

		widgets = {
		    'name': forms.TextInput(attrs={
		        'class': 'form-control',
		        'placeholder': 'lorem ipsum',
		    }),
		}

marque/views.py
from django.shortcuts import render
from voiture.models import Marque, Voiture
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView,DeleteView
from .forms import MarqueForm
from django.contrib.auth.mixins import PermissionRequiredMixin

# Create your views here.


class MarqueDetailView(DetailView):
	template_name = 'Marque/detail.html'
	marques = Marque.objects.all()
	def get(self, request, *args, **kwargs):
		voitures = Voiture.objects.filter(marque=self.kwargs['pk'])
		marque_voiture = Marque.objects.get(pk=self.kwargs['pk'])
		return render(request, self.template_name, {'marques': self.marques, 'voitures': voitures, 'marque_voiture': marque_voiture})


class MarqueListView(ListView):
	model = Marque
	template_name = 'Marque/list.html'
	context_object_name = 'marques'


class MarqueCreateView(CreateView):
	model = Marque
	template_name = "Marque/create.html"
	form_class = MarqueForm
	success_url = reverse_lazy('marque:list')


class MarqueUpdateView(UpdateView):
	model = Marque
	template_name = "Marque/create.html"
	form_class = MarqueForm
	success_url = reverse_lazy('marque:list')


class MarqueDeleteView(DeleteView):
	model = Marque
	success_url = reverse_lazy('marque:list')

templates/Marque/create.html
{% extends "base.html" %}

{% block title %}Ajouter une marque{% endblock %}

{% block content %}
	<h1 class="fs-3 fw-bolder text-center">Ajouter une marque</h1>
	<hr class="offset-md-4 offset-3 border-2 text-primary col-6 col-md-4  rounded-pill" style="height: 3px;">
	<div class="offset-md-2 offset-sm-2">
		<form method="post" class="offset-md-1 row col-md-8 col-sm-8 col px-3 shadow pt-3 mx-2 mx-md-5" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
                <label class="form-label">{{ field.label }}</label>
                {{ field }}
                <small id="{{ field.label }}" class="form-text text-muted invalid-feedback"></small>
            </div>				
            {% endfor %}
            <input class="btn btn-primary col-6 col-md-8 offset-md-2 offset-3 mb-3" type="submit" value="Ajouter marque" id="">
		</form>
	</div>
{% endblock %}

templates/Marque/detail.html
{% extends 'base.html' %}

{% block title %}Marque{% endblock %}

{% block content %}
<div class="row mx-3">

	<div class=" col-md-3 mb-3 justify-content-center">
		<ul class="list-group">
		    {% for marque in marques %}
		    	{% if marque_voiture == marque %}
		    		<li class="list-group-item active shadow"> <a href=" {% url 'marque:detail' marque.pk %} " class="text-decoration-none text-light">{{ marque.name }} </a> </li>
		    	{% else %}
		    		<li class="list-group-item"> <a href=" {% url 'marque:detail' marque.pk %} " class="text-decoration-none">{{ marque.name }} </a> </li>
		    	{% endif %}
		    {% endfor %}
		</ul>
	</div> 
	<div class="col-md-9 mb-3">
		<div class="row mb-3 mx-1 shadow">
			<div class="offset-4 fs-1 pt-2"> 
				{{ marque_voiture.name }}
			</div>
			<hr class="offset-3 border-2 text-primary col-6 rounded-pill" style="height: 3px;">
		</div>
		<div class="row">
		{% for voiture in voitures %}
			<div class="col-md-4 mb-3 d-flex">
				<div class="card h-100 px-2 h-75 pt-1">
				  <img src=" {{ voiture.image.url }} " class="card-img-top h-75 text-center" alt="...">
				  <div class="card-body d-flex flex-column">
				  	<div class="mt-auto mx-auto">
					    <h5 class="fs-6"> {{ voiture.marque }} {{ voiture.name }} </h5>
					    <a href=" {% url 'voiture:detail' voiture.pk %} " class="btn btn-primary offset-3">Plus <i class="bi bi-arrow-right-circle text-light"></i></a>
				    </div>
				  </div>
				</div>
			</div>
		{% endfor %}
		</div>
	</div>
</div>

{% endblock content %}

templates/Marque/list.html
{% extends 'base.html' %}

{% block title %}Marque{% endblock %}

{% block content %}
<div class="row mx-3 mt-5">
	<div class="row">
		{% for marque in marques %}
			<div class="col-sm-6 mb-3">
			<div class="card">
				<div class="card-body">
				<h5 class="card-title text-center">{{ marque.name }}</h5>
				<p class="card-text"></p>
				<a href="{% url 'marque:detail' marque.pk %}" class="btn btn-primary offset-4 offset-xxl-5 offset-xl-4">Voir Plus</a>
				</div>
			</div>
			</div>
		{% endfor %}
	</div>
</div>

{% endblock content %}