concessionnaire/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from voiture import views as voiture_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', voiture_views.VoitureView.as_view(), name='index'),
    path('assistance/', voiture_views.AssistanceView.as_view(), name='assistance'),
    path('concession/', voiture_views.ConcessionView.as_view(), name='concession'),
    path('voiture/', include('voiture.urls', namespace='voiture')),
    path('marque/', include('marque.urls', namespace='marque')),
    #path('__debug__/', include('debug_toolbar.urls')),
    path('utilisateurs/', include('utilisateurs.urls', namespace='utilisateurs')),
] 


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


'''
On utilise souvent un nom pour les apps quand on écrit plusieurs applications
et dont les noms des urls spnt les memes. Alors les app_namme permettent de se
rediriger vers cet url selin de nom de l'app defini
'''

marque/urls.py
from django.urls import path
from . import views


app_name = 'marque'


urlpatterns = [
	# post views
	path('<int:pk>/', views.MarqueDetailView.as_view(), name='detail'),
	path('', views.MarqueListView.as_view(), name='list'),
	path('add/', views.MarqueCreateView.as_view(), name='add'),
	path('update/<int:pk>/', views.MarqueUpdateView.as_view(), name='update'),
	path('delete/<int:pk>/', views.MarqueDeleteView.as_view(), name="delete"),
]

voiture/urls.py
from django.urls import path
from . import views


app_name = 'voiture'


urlpatterns = [
	# post views
	#path('', views.VoitureView.as_view(), name='index'),
	path('<int:pk>/', views.VoitureDetail.as_view(), name='detail'),
	path('list/', views.VoitureList.as_view(), name='list'),
	path('add/', views.VoitureAdd.as_view(), name='add'),
	path('search/', views.VoitureSearchView.as_view(), name='search'),
	path('update/<int:pk>/', views.VoitureUpdate.as_view(), name='update'),
	path('delete/<int:pk>/', views.VoitureDelete.as_view(), name="delete"),
	path('<int:pk>/achat/', views.VoitureAchat.as_view(), name='payement'),	
]

voiture/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Marque(models.Model):
	name = models.CharField(max_length=120)
		
	def __str__(self):
		return self.name


class Voiture(models.Model):
	marque = models.ForeignKey(Marque, on_delete=models.CASCADE)
	name = models.CharField(max_length=120)
	price = models.DecimalField(max_digits=19, decimal_places=2) 
	image = models.FileField(upload_to='uploads/')

	def __str__(self):
		return '%s %s'%(self.marque, self.name)

	def get_absolute_url(self):
		return reverse('voiture:detail', kwargs={'pk': self.pk})

voiture/forms.py
from django import forms
from .models import Marque, Voiture

class VoitureForm(forms.ModelForm):

	class Meta:

		model = Voiture

		fields = '__all__'

		widgets = {
		    'name': forms.TextInput(attrs={
		        'class': 'form-control',
		        'placeholder': 'lorem ipsum',
		    }),

		    'price': forms.NumberInput(
		    	attrs={
		    		'class': 'form-control',
		    		'placeholder': '123457.90',
		    	}
		    ),

		    'marque': forms.Select(
		    	attrs={
		    		'class': 'form-control',
		    	}
		    ),

		    'image': forms.FileInput(
		    	attrs={
		    		'class': 'form-control',
		    	}
		    ),
		}

voiture/views.py
from django.shortcuts import render
from .models import Marque, Voiture
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .forms import VoitureForm
from django.urls import reverse_lazy
from django.db.models import Q
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView,DeleteView

# Create your views here.

class VoitureView(ListView):
    template_name='Voiture/index.html'
    marques = Marque.objects.all()
    voitures = Voiture.objects.all()[:3]

    def get(self, request):
        return render(request, self.template_name, {'voitures': self.voitures, 'marques': self.marques,})


class ConcessionView(View):
    template_name="Voiture/concession.html"
    marques = Marque.objects.all()

    def get(self, request):
        return render(request, self.template_name, {'marques': self.marques})


class VoitureSearchView(View):
    template_name = "Voiture/search.html"
    marques = Marque.objects.all()

    def get(self, request,*args, **kwargs):
        return render(request, self.template_name, {'marques': self.marques})

    def post(self, request, *args, **kwargs):
        query = request.POST.get("rechercher")
        if query == "" or query == " ":
            object_list = None
        else :
            object_list = Voiture.objects.filter(
                Q(name__icontains=query) | Q(marque__name__icontains=query)
            )
        return render(request, self.template_name, {'object_list': object_list, 'marques': self.marques})


class AssistanceView(View):
    template_name = 'Voiture/assistance.html'
    marques = Marque.objects.all()

    def get(self, request):
        return render(request, self.template_name, {'marques': self.marques})


class VoitureList(ListView):
    template_name = 'Voiture/list.html'
    voitures = Voiture.objects.all()
    marques = Marque.objects.all()

    def get(self, request):
        return render(request, self.template_name, {'marques': self.marques, 'voitures': self.voitures})


class VoitureDetail(DetailView):
    template_name = 'Voiture/detail.html'
    marques = Marque.objects.all()

    def get(self, request, *args, **kwargs):
        voiture = Voiture.objects.get(pk=self.kwargs['pk'])
        return render(request, self.template_name, {'marques': self.marques, 'voiture': voiture})
        

class VoitureAdd(PermissionRequiredMixin, CreateView):	
    permission_required = 'voiture.add_voiture'	
    model = Voiture
    template_name = 'Voiture/add.html'
    form_class = VoitureForm
    success_url = reverse_lazy('voiture:list')


class VoitureUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'voiture.change_voiture'		
    model = Voiture
    template_name = 'Voiture/update.html'
    form_class = VoitureForm
    success_url = reverse_lazy('voiture:list')


class VoitureDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'voiture.delete_voiture'		
    model = Voiture
    success_url = reverse_lazy('voiture:list')


class VoitureAchat(LoginRequiredMixin, View):
    login_required=True
    template_name = 'Voiture/payement.html'
    marques = Marque.objects.all()

    def get(self, request, *args, **kwargs):
        voiture = Voiture.objects.get(pk=self.kwargs['pk'])
        return render(request, self.template_name, {'voiture': voiture, 'marques': self.marques})

templates/Voiture/add.html
{% extends 'base.html' %}

{% block title %}Voiture ajouter{% endblock %}

{% block content %}
<div class="mt-3 mx-3">
	<h1 class="text-center fs-3 fw-bolder">Ajouter une voiture</h1>
	<hr class="offset-md-4 offset-3 border-2 text-primary col-6 col-md-4  rounded-pill" style="height: 3px;">
	<div class="offset-md-2">
		<form method="post" class="offset-md-1 row col-md-8 col-sm-6 col px-3 shadow pt-3 mx-2 mx-md-5" enctype="multipart/form-data">
			{% csrf_token %}
			{% for field in form %}
			<div class="mb-3">
				<label class="form-label">{{ field.label }}</label>
				{{ field }}
			</div>
			{% endfor %}
			<input type="submit" class="btn btn-primary col-6 col-md-8 offset-md-2 offset-3 mb-3" value="Ajouter Voiture">
		</form>
	</div>
</div>
{% endblock content %}

templates/Voiture/assistance.html
{% extends 'base.html' %} {% block title %}Assistance{% endblock %} {% block content %}
<div class="row">
    <form method="post" class="row offset-md-2 offset-sm-1 ps-4 row col-12 px-3 mt-5 border rounded=3 pt-3 col-sm-10 col-md-8 col-lg-8 col-xl-8" enctype="multipart/form-data">
        <div class="row form-group mb-3">
            <h3 class="fs-5 text-center">Contactez notre assistance pour plus d'informations</h3>
        </div>
        {% csrf_token %}
        <div class="row form-group mb-3">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
        </div>
        <div class="row mb-3">
            <div class="col row me-1">
                <label for="first_name">Nom :</label>
                <input type="text" class="form-control" placeholder="Doe" name="first_name" id="first_name">
            </div>
            <div class="col row ms-1">
                <label for="last_name">Prenom :</label>
                <input type="text" class="form-control" placeholder="John" name="last_name" id="last_name">
            </div>
        </div>
        <div class="row form-group mb-3">
            <label for="message">Posez votre question</label>
            <textarea class="form-control" id="message" name="message" rows="4"></textarea>
        </div>
        <div class="row form-group justify-content-center">
            <input type="submit" class="btn btn-primary col-6 " value="Envoyer un message">
            <p class="form-text py-2">Veuillez remplir le formulaire ci-dessus pour nous contacter par mail. Nous vous repondrons dans le plus bref delai possible.</p>
        </div>
    </form>
</div>
{% endblock content %}

templates/Voiture/concession.html
{% extends 'base.html' %} {% block title %}Recherche{% endblock %} {% block content %}
<div class="row">
    <form method="get" class="offset-md-2 col-md-8 border" enctype="multipart/form-data">
        <div class="row form-group mb-3">
            <h3 class="fs-5 text-center">Rechercher une coincession</h3>
        </div>
        {% csrf_token %}
        <div class="row form-group d-flex justify-content-between mx-2 mb-3">
            <input type="search" class="form--control col-6" name="rechercher" placeholder="Entrez votre localite">
            <input type="submit" class="btn btn-primary offset-1 col-4" value="Rechercher">
        </div>
    </form>
</div>
<div class="offset-md-2 col-md-8 mt-5 px-2 resultat">
    {% comment %}
    {% for object in object_list %}
       
    {% endfor %}
    {% endcomment %}
</div>
{% endblock content %}

templates/Voiture/detail.html
{% extends 'base.html' %}

{% block title %}Voiture Detail{% endblock %}

{% block content %}
<div class="row mx-3">
	<div class="row-cols-1 col-md-2 mb-3">
		<ul class="list-group">
		    {% for marque in marques %}
		    	<li class="list-group-item"> <a href=" {% url 'marque:detail' marque.pk %} " class="text-decoration-none">{{ marque.name }} </a> </li>
		    {% endfor %}
		</ul>
	</div> 

	<div class=" row-cols-1 offset-md-1 card shadow-custom border-0 col-md-9 mx-auto">
		<div class="row justify-content-center">
			<div class="row-cols-1 col-md-6 col-xxl-8 col-lg-7 col-xl-7">
				{% if voiture.marque.name == "Lamborghini" %}
				<a href="https://www.lamborghini.com/en-en" class="text-decoration-none" target="_blank">
				{% elif voiture.marque.name == "Aston Martin" %}
				<a href="https://www.astonmartin.com/fr/" class="text-decoration-none" target="_blank">
				{% elif voiture.marque.name == "Rolls Royce" %}
				<a href="https://www.rolls-roycemotorcars.com/en_GB/home.html" class="text-decoration-none" target="_blank">
				{% elif voiture.marque.name == "Ferrari" %}
				<a href="https://www.ferrari.com/en-BJ" class="text-decoration-none" target="_blank">
				{% elif voiture.marque.name == "Mercedes" %}
				<a href="https://www.mercedes-benz.com/en/" class="text-decoration-none" target="_blank">
				{% else %}
				<a href="#">
				{% endif %}
					<img src="{{ voiture.image.url }}" alt=""class="img-fluid rounded-3 h-75 w-100">
				</a>
			</div>
			<div class="row-cols-1 col-md-6 col-xxl-4 col-lg-5 col-xl-5">
				<div class="top">
					<h2 class="mt-4 font-weight-bold text-grey"> {{ voiture.name }} {{ voiture.marque }} </h2>
					<div>
						<span class="font-weight-bold text-grey"> Vitesse: 320km/h</span> 
					</div>
					<div>
						<span class="font-weight-bold text-grey">Reservoir:</span> 10l
					</div>
					<div>
						<span class="font-weight-bold text-grey">Prix:</span> {{ voiture.price }} FCFA
					</div>
				</div>
				<div class="mt-3 form-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
				<hr>
				<div class="mb-4">
					<form class="rounded-pill shadow">
						<span class="input-group add-to-cart shadow-custom">
							<div class="input-group-prepend">
								<span class="input-group-text font-weight-bold px-3 btn btn-block price">${{ voiture.prix }}</span>
							</div>

							<span id="minus" class="input-group-text button_minus px-4" style="cursor: pointer;">-</span>

							<input type="number" value="1" class="form-control text-center px-3 valeur">

							<span id="plus" class="input-group-text button_plus px-4" style="cursor: pointer;">+</span>

							<div class="input-group-append pe-3">
								<a href="{% url 'voiture:payement' voiture.pk %}" class="text-decoration-none">
									<button class="btn btn-danger px-4 reduce_padding" data-toggle="tooltip" data-placement="top" title="Reserver un essai">
										<i class="bi bi-cart-check-fill text-light"></i>
									</button>
								</a>
							</div>
						</span>
					</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock content %}

{% comment %}
	{% extends 'base.html' %} {% block title %}Voiture List{% endblock %} {% block content %}

<div class="">
    <div class="row mx-3">
        <div class="col-3 mb-3">
            <ul class="list-group">
                {% for marque in marques %}
                <li class="list-group-item"> <a href=" {% url 'marque:detail' marque.pk %} " class="text-decoration-none">{{ marque.name }} </a> </li>
                {% endfor %}
            </ul>
        </div>
        <div class="row col-9">
            <div class="row fs-3 fw-bolder">
                <p class="text-center">Choississez votre perle rare dans chez nous</p>
            </div>
            <div class="row d-flex ">
            {% for voiture in voitures %}
            <div class="mb-3 col col-sm-6 col-md-4 col-lg-4 col-xl-4 col-xxl-4 ">
                <div class="card h-100 px-2 w-100">
                    <img src=" {{ voiture.image.url }} " class="card-img-top h-50" alt="...">
                    <div class="card-body d-flex flex-column">
                        <div class="mt-auto mx-auto">
                            <h5 class="card-title"> {{ voiture.marque }} {{ voiture.name }} </h5>
                            <a href=" {% url 'voiture:detail' voiture.pk %} " class="btn btn-primary offset-3">Plus <i class="bi bi-arrow-right"></i> </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}
{% endcomment %}

templates/Voiture/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Bienvenue{% endblock %}

{% block content %}
<div class="mx-3">
	<div class="row ">
		<div id="carouselExampleControls" class="carousel slide " data-bs-ride="carousel">
		    <div class="carousel-inner">
		        <div class="carousel-item active height-25r">
		            <img src="{% static "images/carousel-1.jpg"%}" class="img-fluid d-block w-100" alt="...">

		            <div class="carousel-caption d-none d-md-block text-wite">
				        <h5>Le pouvoir de la vitesse</h5>
				        <p>Quand on ne sait pas où on va, la vitesse du déplacement ne compte plus.
						</p>
				    </div>
		        </div>
			    <div class="carousel-item height-25r">
			        <img src="{% static "images/carousel-2.jpg"%}" class="img-fluid d-block w-100" alt="...">

			        <div class="carousel-caption d-none d-md-block text-wite">
				        <h5>Profitez de la vie avec la Lamborghini urus</h5>
				        <p>Idéalement nous sommes ce que nous pensons. Dans la réalité, nous sommes ce que nous accomplissons.</p>
				    </div>
			    </div>
			    <div class="carousel-item height-25r">
			        <img src="{% static "images/carousel-3.jpg"%}" class="img-fluid d-block w-100" alt="...">

			        <div class="carousel-caption d-none d-md-block text-wite">
				        <h5>Le luxe, c'est la liberte</h5>
				        <p>La vitesse est la forme d'extase dont la révolution technique a fait cadeau à l'homme.</p>
				    </div>
			    </div>
		    </div>
		    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
		    	<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		    	<span class="visually-hidden">Previous</span>
		    </button>
		    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
		    	<span class="carousel-control-next-icon" aria-hidden="true"></span>
		    	<span class="visually-hidden">Next</span>
		    </button>
		</div>
	</div>

	<div class="row mx-auto mt-5 bg-light bg-opacity-25">
        <div class="col-6 col-md-3 col-sm-6 border fw-bolder">
			<a href="#" class="text-decoration-none text-dark fw-bolder">
				<div class="py-5 text-center"><span class="rounded-circle border border-dark p-4"><i class="bi bi-wrench-adjustable fs-3 text-primary"></span></i></div>
				<div class="pb-2 text-center">Construire & Prix</div>
			</a>
    	</div>
    	<div class="col-6 col-md-3 col-sm-6 border fw-bolder">
			<a href=" {% url 'concession' %} " class="text-decoration-none text-dark fw-bolder">
				<div class="py-5 text-center"><span class="rounded-circle border border-dark p-4"><i class="bi bi-shop fs-3 text-primary"></i></span></div>
				<div class="pb-2 text-center">? une concession</div>
			</a>
    	</div>
    	<div class="col-6 col-md-3 col-sm-6 border fw-bolder">
			<a href=" {% url 'voiture:search' %} " class="text-decoration-none text-dark fw-bolder">
				<div class="py-5 text-center"><span class="rounded-circle border border-dark p-4"><i class="bi bi-search fs-3 text-primary"></i></span></div>
				<div class="pb-2 text-center">Rechercher</div>
			</a>
    	</div>
    	<div class="col-6 col-md-3 col-sm-6 border fw-bolder">
			<a href=" {% url 'assistance' %} " class="text-decoration-none text-dark fw-bolder">
				<div class="py-5 text-center"><span class="rounded-circle border border-dark p-4"><i class=" bi bi-person-badge fs-3 text-primary text-center"></i></span></div>
				<div class="pb-2 text-center">
					Assistance
				</div>
			</a>
    	</div>
    </div>

    <div class="row my-4">
    	<h2 class="text-center fs-2 fw-normal">LE POUVOIR D’ATTRACTION</h2>
    	<p class="col-8 offset-2 fw-600">
			Une allure féline qui se distingue au premier regard.&nbsp;
			Une expérience de conduite sans cesse renouvelée.&nbsp;
			Notre conncession ALPHA_ONE séduit année après année par le raffinement de son espace intérieur et l’élégance de ses lignes extérieures.&nbsp;
		</p> 
    </div>
	
	<div class="row">
		{% for voiture in voitures %}
			<div class="col-md-4">
				<div class="card card-body h-100 p-0 rounded-3">
				  	<img src=" {{ voiture.image.url }} " class="img-fluid rounded-3 h-100" alt="...">
				  	<div class="carousel-caption d-block">
					    <h5 class="card-title"> {{ voiture.marque }} {{ voiture.name }} </h5>
					    <a href=" {% url 'voiture:detail' voiture.pk %} " class="text-decoration-none fw-bolder">Voir plus <i class="bi bi-arrow-right-circle"></i></a>
				    </div>
				</div>
			</div>
		{% endfor %}
		<div class="offset-5 col-md-3 mt-2">
			<a href=" {% url 'voiture:list' %} " class="btn btn-light rounded-pill fw-bolder">Explorer tous les vehicules</a>
		</div>
	</div>
</div>
{% endblock content %}

templates/Voiture/list.html
{% extends 'base.html' %} {% block title %}Voiture List{% endblock %} {% block content %}

<div class="">
    <div class="row mx-3">
        <div class=" col-3 mb-3">
            <ul class="list-group">
                {% for marque in marques %}
                <li class="list-group-item"> <a href=" {% url 'marque:detail' marque.pk %} " class="text-decoration-none">{{ marque.name }} </a> </li>
                {% endfor %}
            </ul>
        </div>
        <div class="row col-9">
            <div class="row fs-3 fw-bolder">
                <p class="text-center">Choississez votre perle rare dans chez nous</p>
            </div>
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 row-cols-xxl-4">
                {% for voiture in voitures %}
                <div class=" mb-3 col d-flex ">
                    <div class="card h-100 px-2 w-100">
                        <img src=" {{ voiture.image.url }} " class="card-img-top h-50" alt="...">
                        <div class="card-body d-flex flex-column">
                            <div class="mt-auto mx-auto">
                                <h5 class="card-title"> {{ voiture.marque }} {{ voiture.name }} </h5>
                                <a href=" {% url 'voiture:detail' voiture.pk %} " class="btn btn-primary offset-3">Plus <i class="bi bi-arrow-right"></i> </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/Voiture/payement.html
{% extends 'base.html' %}

{% block content %}
<div class="row g-5 mx-3">
  <div class="col-md-5 col-lg-4 order-md-last">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
      <span class="text-primary">Your cart</span>
      <span class="badge bg-primary rounded-pill">1</span>
    </h4>
    <ul class="list-group mb-3">
      <li class="list-group-item d-flex justify-content-between lh-sm">
        <div>
          <h6 class="my-0">{{ voiture.marque }}</h6>
          <small class="text-muted">{{ voiture.name }}</small>
        </div>
        <span class="text-muted">FCFA {{ voiture.price }}</span>
      </li>
      <li class="list-group-item d-flex justify-content-between">
        <span>Total (FCFA)</span>
        <strong>FCFA {{ voiture.price }}</strong>
      </li>
    </ul>

    <form class="card p-2">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="Promo code">
        <button type="submit" class="btn btn-secondary">Redeem</button>
      </div>
    </form>
  </div>
  <div class="col-md-7 col-lg-8">
    <h4 class="mb-3">Billing address</h4>
    <form class="needs-validation" enctype="multipart/form-data" novalidate>
      <div class="row g-3">
        <div class="col-sm-6">
          <label for="firstName" class="form-label">First name</label>
          <input type="text" class="form-control" id="firstName" placeholder="" value=" {{ user.first_name }} " required>
          <div class="invalid-feedback">
            Valid first name is required.
          </div>
        </div>

        <div class="col-sm-6">
          <label for="lastName" class="form-label">Last name</label>
          <input type="text" class="form-control" id="lastName" placeholder="" value="{{ user.last_name }}" required>
          <div class="invalid-feedback">
            Valid last name is required.
          </div>
        </div>

        <div class="col-12">
          <label for="username" class="form-label">Username</label>
          <div class="input-group has-validation">
            <span class="input-group-text">@</span>
            <input type="text" class="form-control" id="username" placeholder="Username" value="{{ user.username }}" required>
          <div class="invalid-feedback">
              Your username is required.
            </div>
          </div>
        </div>

        <div class="col-12">
          <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
          <input type="email" class="form-control" id="email" placeholder="you@example.com" value="{{ user.email }}">
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>

        <div class="col-12">
          <label for="address" class="form-label">Address</label>
          <input type="text" class="form-control" id="address" placeholder="1234 Main St" required>
          <div class="invalid-feedback">
            Please enter your shipping address.
          </div>
        </div>

        <div class="col-12">
          <label for="address2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>
          <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
        </div>

        <div class="col-md-5">
          <label for="country" class="form-label">Country</label>
          <select class="form-select" id="country" required>
            <option value="">Choose...</option>
            <option>United States</option>
          </select>
          <div class="invalid-feedback">
            Please select a valid country.
          </div>
        </div>

        <div class="col-md-4">
          <label for="state" class="form-label">State</label>
          <select class="form-select" id="state" required>
            <option value="">Choose...</option>
            <option>California</option>
          </select>
          <div class="invalid-feedback">
            Please provide a valid state.
          </div>
        </div>

        <div class="col-md-3">
          <label for="zip" class="form-label">Zip</label>
          <input type="text" class="form-control" id="zip" placeholder="" required>
          <div class="invalid-feedback">
            Zip code required.
          </div>
        </div>
      </div>

      <hr class="my-4">

      <div class="form-check">
        <input type="checkbox" class="form-check-input" id="same-address">
        <label class="form-check-label" for="same-address">Shipping address is the same as my billing address</label>
      </div>

      <div class="form-check">
        <input type="checkbox" class="form-check-input" id="save-info">
        <label class="form-check-label" for="save-info">Save this information for next time</label>
      </div>

      <hr class="my-4">

      <h4 class="mb-3">Payment</h4>

      <div class="my-3">
        <div class="form-check">
          <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked required>
          <label class="form-check-label" for="credit">Credit card</label>
        </div>
        <div class="form-check">
          <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required>
          <label class="form-check-label" for="debit">Debit card</label>
        </div>
        <div class="form-check">
          <input id="paypal" name="paymentMethod" type="radio" class="form-check-input" required>
          <label class="form-check-label" for="paypal">PayPal</label>
        </div>
      </div>

      <div class="row gy-3">
        <div class="col-md-6">
          <label for="cc-name" class="form-label">Name on card</label>
          <input type="text" class="form-control" id="cc-name" placeholder="" required>
          <small class="text-muted">Full name as displayed on card</small>
          <div class="invalid-feedback">
            Name on card is required
          </div>
        </div>

        <div class="col-md-6">
          <label for="cc-number" class="form-label">Credit card number</label>
          <input type="text" class="form-control" id="cc-number" placeholder="" required>
          <div class="invalid-feedback">
            Credit card number is required
          </div>
        </div>

        <div class="col-md-3">
          <label for="cc-expiration" class="form-label">Expiration</label>
          <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
          <div class="invalid-feedback">
            Expiration date required
          </div>
        </div>

        <div class="col-md-3">
          <label for="cc-cvv" class="form-label">CVV</label>
          <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
          <div class="invalid-feedback">
            Security code required
          </div>
        </div>
      </div>

      <hr class="my-4">

      <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
    </form>
  </div>
</div>

{% endblock content %}